COPY C:\ImgPosInst\src\misc\run.lnk "C:\Users\Default\AppData\Roaming" 
COPY "C:\ImgPosInst\src\misc\Meu IP.lnk" "C:\Users\Default\AppData\Roaming" 
COPY C:\ImgPosInst\src\misc\WXE\apply.bat "C:\Users\Default\AppData\Roaming" 
COPY C:\ImgPosInst\src\misc\WXE\version.txt "C:\Users\Default\AppData\Roaming" 
COPY C:\ImgPosInst\src\misc\MeuIP.jar "C:\Users\Default\AppData\Roaming" 
COPY C:\ImgPosInst\src\misc\oemlogo.png "C:\Users\Default\AppData\Roaming" 
COPY C:\ImgPosInst\src\misc\run.lnk "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp" 
COPY "C:\ImgPosInst\src\misc\Meu IP.lnk" "C:\Users\Default\Desktop"